[General]
background=assets/background.jpg

# Colors
accentColor=#4169E1
backgroundColor=#00001A
textPrimaryColor=#CDD6F4
textSecondaryColor=#FFFFFF
textTertiaryColor=#8EA8F6

placeholderColor=#4A5B82
warnColor=#E0AF68

cardBgColor=#99151A26
inputBgColor=#990F121B

# borders
inputBorderColor=#2A3958
inputBorderActiveColor=#5C82F2

# buttons
btnPrimaryBgColor=#2C3E6B
btnSecondaryBgColor=#222C3D

use24HourClock=false
fontFamily=
